enum ActionType {
  FETCH_FORMS = 'FETCH_FORMS',
  FETCH_FORMS_SUCCESS = 'FETCH_FORMS_SUCCESS',
  FETCH_FORMS_FAILURE = 'FETCH_FORMS_FAILURE',
  SUBMIT_FORM = 'SUBMIT_FORM',
  SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS',
  SUBMIT_FORM_FAILURE = 'SUBMIT_FORM_FAILURE',
  DELETE_FORM = 'DELETE_FORM',
  DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS',
  DELETE_FORM_FAILURE = 'DELETE_FORM_FAILURE',
  UPDATE_FORM = 'UPDATE_FORM',
  UPDATE_FORM_SUCCESS = 'UPDATE_FORM_SUCCESS',
  UPDATE_FORM_FAILURE = 'UPDATE_FORM_FAILURE',
  SEARCH_FORM = 'SEARCH_FORM',
  SEARCH_FORM_SUCCESS = 'SEARCH_FORM_SUCCESS',
  SEARCH_FORM_FAILURE = 'SEARCH_FORM_FAILURE',
}

export default ActionType;
